######################################################################
# Automatically generated by qmake (2.01a) Pn 26. pa? 18:49:02 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
FORMS += dialog.ui
SOURCES += dialog.cpp main.cpp
RESOURCES += images.qrc
